import React from 'react';
import { QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';
import { AppProps } from 'next/app';
import Head from 'next/head';
import Header from '@components/header';
import { GlobalStyle } from '../styles/globals-style';
import { queryClient } from '@react-query/queryClient';

// const queryClient = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <QueryClientProvider client={queryClient}>
        <ReactQueryDevtools />
        <Head>
          <title>FAQ</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <GlobalStyle />
        <Header />
        <Component {...pageProps} />
      </QueryClientProvider>
    </>
  );
}

export default MyApp;
